# fly.toml app configuration file generated for scrabble-api on 2023-07-30T02:09:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scrabble-api"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
